name: Static analysis
on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches: [9.x]
jobs:
  static-analysis:
    name: Static analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        run: |
          sudo update-alternatives --set php /usr/bin/php7.4
      - name: Setup SSH auth & Github config
        run: |

          mkdir -p ~/.ssh
          echo $SSH_HOST_KEY >> ~/.ssh/known_hosts
          echo $SSH_HOST_KEY_GH >> ~/.ssh/known_hosts
        env:
          # Find out the host-key via "ssh-keyscan -p 22 github.com | grep ssh-rsa" and pre-set it.
          SSH_HOST_KEY: >
            bitbucket.org ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw==
          SSH_HOST_KEY_GH: >
            github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
      - name: "Determine composer cache directory"
        id: "determine-composer-cache-directory"
        run: "echo \"::set-output name=directory::$(composer config cache-dir)\""
      - name: "Cache dependencies installed with composer"
        uses: actions/cache@v2.1.5
        with:
          path: "${{ steps.determine-composer-cache-directory.outputs.directory }}"
          key: ${{ runner.os }}-composer-v1-${{ hashFiles('./composer.json') }}
          restore-keys: |
            ${{ runner.os }}-composer-v1
      - name: Install composer dependencies.
        env:
          COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{secrets.COMPOSER_AUTH}}"} }'
        run: |
          ls -a
          composer config platform-check false
          composer install
      - name: Run the PHPUnit tests and code style checks
        run: |
          ./vendor/bin/phpunit
          composer cs
